joints:
  name:
    - second_arm_0_joint
    - second_arm_1_joint
    - second_arm_2_joint
    - second_arm_3_joint
    - second_arm_4_joint
    - second_arm_5_joint
    - second_arm_6_joint
    - first_arm_0_joint
    - first_arm_1_joint
    - first_arm_2_joint
    - first_arm_3_joint
    - first_arm_4_joint
    - first_arm_5_joint
    - first_arm_6_joint
    - third_arm_0_joint
    - first_arm_1_joint
    - third_arm_2_joint
    - third_arm_3_joint
    - third_arm_4_joint
    - third_arm_5_joint
    - third_arm_6_joint
    - fourth_arm_0_joint
    - fourth_arm_1_joint
    - fourth_arm_2_joint
    - fourth_arm_3_joint
    - fourth_arm_4_joint
    - fourth_arm_5_joint
    - fourth_arm_6_joint
  position:

    - -1.0762380361557007 
    - 0.8758195638656616 
    - 1.6818004846572876
    - -1.2367960214614868 
    - -0.21789032220840454 
    - 1.5499436855316162
    - 2.9348559379577637
    - -0.2609390318393707
    - 0.0860038548707962
    - 0.38461998105049133
    - -1.4664061069488525
    - -0.5065183043479919
    - 1.3230632543563843
    - 1.780334234237671
    - -1.0762380361557007 
    - 0.8758195638656616 
    - 1.6818004846572876
    - 1.2367960214614868 
    - 0.21789032220840454 
    - -1.5499436855316162
    - 2.9348559379577637
    - -0.2609390318393707
    - 0.0860038548707962
    - 0.38461998105049133
    - 1.4664061069488525
    - 0.5065183043479919
    - -1.3230632543563843
    - 1.780334234237671